### ISSUE TITLE
Parameter Select not searching after upgrade from 2.2.5 to 2.3.1

### ISSUE THREAD

**Issue by luzidl** [neo4j-labs/neodash#563]
After upgrading a couple of Dashboards from 2.2.5 to 2.3.1 parameter select seems to not take input that is stored as number in the database. Cut and paste of an accountID (data type: number, eg. 55716) provided a result in NeoDash 2.2.5, but did not find it in 2.3.1. Searching by typing the same account ID number does not work either. (See graphics attached below):

- NeoDash version: 2.2.5 --> 2.3.1
- Neo4j Database version: 4.4. 3 (Enterprise).

- **Steps to reproduce**
- Migrate a DB (4.4.3) from NeoDash 2.2.5 to 2.3.1 using a parameter select visualization on a node property that is a data type number and try to search a number in both.

- Expected: Number is found immediately if pasted or partially if it it typed.

NeoDash 2.2.5: 
<img width="1125" alt="image" src="https://github.com/neo4j-labs/neodash/assets/8035021/1babbb20-8ad2-484e-98dc-ed2161b94c0b">

NeoDash 2.3.1:
<img width="1097" alt="image" src="https://github.com/neo4j-labs/neodash/assets/8035021/12cb3ddb-c406-4a64-a2b4-f5d43922dc5f">

**Comment by BennuFire** [comment]
Hi @luzidl ,

This should be already fixed on the version 2.3.2 that we are expecting to release today 😀

**Comment by BennuFire** [comment]
You get a preview of it on 
http://neodash-test.graphapp.io.s3-website-us-west-1.amazonaws.com/

**Comment by BennuFire** [comment]
I just released 2.3.2. Can you confirm this is solved for you now?

**Comment by luzidl** [comment]
Nope, it is still not working. Same as before, no results found when pasting a number or typing a number.

**Comment by luzidl** [comment]
@BennuFire any thoughts when this will be fixed? :-) It is an essential functionality in my AML&Fraud Demo. Thx in advaned!

**Comment by gcthys** [comment]
Hi @luzidl,

This bug worried me, so I tried to replicatie it on my dashboard. I took a random property of a random node with type "integer" and it seems to work fine:

![image](https://github.com/neo4j-labs/neodash/assets/68611501/10008783-e60e-4577-82ef-9f80b4aef2bf)

Are you sure you didn't inadvertently change something in the settings? (just trying to think along...)

Guido

**Comment by BennuFire** [comment]
@luzidl I'm still trying to replicate the issue with no success. Can you share you dashboard json?

**Comment by luzidl** [comment]
For sure @BennuFire, will send it via email in a moment.

**Comment by BennuFire** [comment]
Fixed on 2.3.5

**Comment by luzidl** [comment]
@BennuFire, not entirely as I can see. I can not find the accountIds, but the queries are not finding anything. It seems, that parameter is not set correctly. I also tried to convert it explicitly to a number format and to a String format, but nothing works. Queries do not return any data. See screenshot below:
<img width="1879" alt="Bildschirmfoto 2023-09-25 um 11 16 10" src="https://github.com/neo4j-labs/neodash/assets/8035021/f01f5461-6a9a-468e-9203-f5dea0dad673">

**Comment by BennuFire** [comment]
You are completely right @luzidl , I fixed the dropdown display but missed the propagation. It's fixed here https://github.com/neo4j-labs/neodash/pull/641 . I think we will do another release later this week.
